[tool.poetry]
name = "xremapmanager"
version = "0.1.0"
description = "Manage Xremap"
authors = []

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
installer = "^0.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
